sudo: required
language: generic
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker build -t shannenleong/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shannenleong/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-1
  app: "Docker"
  env: "Docker-env"
  bucket_name: 	"elasticbeanstalk-ap-southeast-1-981359615781"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"