sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t shannenleong/docker-react -f Dockerfile.dev

script:
  - docker run -e CI=true shannenleong/docker-react npm run test